/* Native parity workspaces for the established ScholarVault API. */
(() => {
  const root = () => document.getElementById('moduleContent');
  const esc = v => String(v ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
  const request = async (url, options={}) => { const r=await fetch(url,{headers:{'Content-Type':'application/json',...(options.headers||{})},...options});const d=await r.json().catch(()=>({}));if(!r.ok||d.success===false)throw new Error(d.error||d.message||'Request failed');return d; };
  const card = (title, content) => `<section class="surface-card native-card"><div class="section-head"><h3>${title}</h3></div>${content}</section>`;
  const title = (name, description) => { document.getElementById('legacyTitle').textContent=name; document.getElementById('legacyDescription').textContent=description; };
  const field=(label,id,value='',type='text')=>`<label class="native-field">${label}<input id="${id}" type="${type}" value="${esc(value)}"></label>`;
  const textarea=(label,id,value='',rows=4)=>`<label class="native-field">${label}<textarea id="${id}" rows="${rows}">${esc(value)}</textarea></label>`;
  const notify=(message,type='success')=>window.toast?.(message,type);

  async function templates(){
    title('Templates & Spintax','Your existing campaign library, available in every native composer.');
    let templates=[]; try{templates=JSON.parse(localStorage.getItem('sv_wa_templates')||'[]')}catch{}; const editing=Number(window.__sharedTemplateEditing??-1);
    root().innerHTML=`<div class="native-grid">${card('Template library',`<div class="rule-list">${templates.map((t,i)=>`<div><b>${esc(t.name)}</b><span>${esc(t.body||'')}</span><button class="text-btn" data-edit-template="${i}">Edit</button><button class="text-btn" data-delete-shared-template="${i}">Delete</button></div>`).join('')||'<p>No template is stored in this browser yet. The legacy default catalog will be imported when it is first opened.</p>'}</div>`)}${card('Create template',`<form id="sharedTemplateForm" class="native-form">${field('Template name','sharedTemplateName')}${textarea('Message with Spintax','sharedTemplateBody','Hi {{name}},\n\n{Hello|Greetings} from ScholarVault.',6)}<button class="primary-btn">Save template</button></form>`)}${card('Spintax guide',`<p>Use <b>{one|two|three}</b> to vary a phrase. Use <b>{{name}}</b> for recipient personalization.</p>`)}</div>`;
    const sharedForm=document.getElementById('sharedTemplateForm'), sharedBody=document.getElementById('sharedTemplateBody'); const sharedButton=sharedForm.querySelector('button[type="submit"],button.primary-btn'); if(editing>=0){const current=templates[editing]||{};document.getElementById('sharedTemplateName').value=current.name||'';sharedBody.value=current.body||current.text||'';sharedButton.textContent='Update template';} const sourceHelp=document.createElement('div');sourceHelp.className='spintax-preview';sharedForm.insertBefore(sourceHelp,sharedButton);const refreshPreview=()=>{const source=sharedBody.value||'';const clean=source.replace(/\{\{\s*name\s*\}\}/gi,'');let depth=0,invalid=false;for(const ch of clean){if(ch==='{')depth++;if(ch==='}')depth--;if(depth<0)invalid=true;}const example=source.replace(/\{([^{}|]+(?:\|[^{}]+)+)\}/g,(_,choices)=>{const all=choices.split('|').map(x=>x.trim()).filter(Boolean);return all[Math.floor(Math.random()*all.length)]||'';});sourceHelp.innerHTML=invalid||depth?'<b class="danger-text">Fix unmatched { or } before saving.</b>':`<b>Sample variation</b><span>${esc(example)}</span>`;};sharedBody.oninput=refreshPreview;refreshPreview();sharedForm.onsubmit=e=>{e.preventDefault();const name=document.getElementById('sharedTemplateName').value.trim(),body=sharedBody.value.trim(),clean=body.replace(/\{\{\s*name\s*\}\}/gi,'');let depth=0;for(const ch of clean){if(ch==='{')depth++;if(ch==='}')depth--;}if(!name||!body)return notify('Enter a template name and message','error');if(depth!==0)return notify('Fix unmatched { or } before saving','error');if(editing>=0)templates[editing]={...templates[editing],name,body};else templates.push({name,body});window.__sharedTemplateEditing=-1;localStorage.setItem('sv_wa_templates',JSON.stringify(templates));window.loadTemplateSelectors?.();templates();notify(editing>=0?'Template updated':'Template saved');};
    root().onclick=e=>{const del=e.target.closest('[data-delete-shared-template]');const edit=e.target.closest('[data-edit-template]');if(del){templates.splice(Number(del.dataset.deleteSharedTemplate),1);window.__sharedTemplateEditing=-1;localStorage.setItem('sv_wa_templates',JSON.stringify(templates));window.loadTemplateSelectors?.();templates();}if(edit){window.__sharedTemplateEditing=Number(edit.dataset.editTemplate);templates();}};
  }

  async function blacklist(){
    const d=await request('/api/blacklist'); const rows=d.blacklist||[]; title('Blacklist manager','Contacts here are blocked from all campaign and automated communication.');
    root().innerHTML=`<div class="native-grid">${card('Blocked contacts',`<div class="rule-list">${rows.map(j=>`<div><b>${esc(String(j).replace('@s.whatsapp.net',''))}</b><button class="text-btn" data-unblock="${esc(j)}">Remove block</button></div>`).join('')||'<p>No blocked contacts.</p>'}</div>`)}${card('Add a block',`<form id="blacklistForm" class="native-form">${field('WhatsApp number','blacklistPhone')}<button class="primary-btn">Block contact</button></form>`)}</div>`;
    document.getElementById('blacklistForm').onsubmit=async e=>{e.preventDefault();try{await request('/api/blacklist',{method:'POST',body:JSON.stringify({phone:document.getElementById('blacklistPhone').value})});blacklist();notify('Contact blocked')}catch(x){notify(x.message,'error')}};
    root().onclick=async e=>{const button=e.target.closest('[data-unblock]');if(!button)return;await request('/api/blacklist',{method:'DELETE',body:JSON.stringify({phone:button.dataset.unblock})});blacklist();notify('Block removed');};
  }

  async function calendar(){
    const d=await request('/api/campaigns');const campaigns=Object.entries(d.campaigns||{}).map(([id,c])=>({id,...c})).sort((a,b)=>new Date(a.scheduledFor||a.createdAt||0)-new Date(b.scheduledFor||b.createdAt||0));title('Campaign calendar','Review every queued and completed campaign by schedule.');
    root().innerHTML=card('Scheduled work',`<div class="native-table"><table><thead><tr><th>When</th><th>Campaign</th><th>Status</th><th>Audience</th></tr></thead><tbody>${campaigns.map(c=>`<tr><td>${esc(new Date(c.scheduledFor||c.createdAt||Date.now()).toLocaleString())}</td><td><b>${esc(c.name||c.id)}</b></td><td><span class="tag">${esc(c.status||'scheduled')}</span></td><td>${(c.contacts||[]).length}</td></tr>`).join('')||'<tr><td colspan="4">No scheduled campaigns.</td></tr>'}</tbody></table></div>`);
  }

  async function pipeline(){
    const d=await request('/api/pipeline');const stages=['New','Messaged','Replied','Interested','Registered','Attended'];const grouped=d.pipeline&&typeof d.pipeline==='object'?d.pipeline:Object.fromEntries(stages.map(s=>[s,Array.isArray(d.contacts)?d.contacts.filter(c=>(c.leadStatus||'New')===s):[]]));title('Lead pipeline','Move contacts across the existing CRM stages.');
    root().innerHTML=`<div class="pipeline-grid">${stages.map(stage=>card(stage,`<div class="pipeline-list">${(grouped[stage]||[]).map(c=>`<div class="pipeline-item"><b>${esc(c.name||c.jid)}</b><small>${esc((c.jid||'').split('@')[0])}</small><select data-stage-jid="${esc(c.jid)}">${stages.map(s=>`<option ${s===stage?'selected':''}>${s}</option>`).join('')}</select></div>`).join('')||'<p class="muted">No contacts</p>'}</div>`)).join('')}</div><a class="secondary-btn" href="/api/pipeline/csv">Export pipeline CSV</a>`;
    root().onchange=async e=>{const jid=e.target.dataset.stageJid;if(!jid)return;await request(`/api/contacts/${encodeURIComponent(jid)}/status`,{method:'POST',body:JSON.stringify({status:e.target.value})});notify('Lead stage updated');pipeline();};
  }

  async function history(){
    const d=await request('/api/campaigns');const campaigns=Object.entries(d.campaigns||{}).map(([id,c])=>({id,...c})).sort((a,b)=>new Date(b.createdAt||0)-new Date(a.createdAt||0));title('Campaign history','Delivery progress, failed reasons and non-responder exports.');
    root().innerHTML=card('Campaign records',`<div class="native-table"><table><thead><tr><th>Campaign</th><th>Status</th><th>Sent</th><th>Failed</th><th>Actions</th></tr></thead><tbody>${campaigns.map(c=>`<tr><td><b>${esc(c.name||c.id)}</b><br><small>${esc(new Date(c.createdAt||Date.now()).toLocaleString())}</small></td><td>${esc(c.status||'')}</td><td>${c.sentCount||0}</td><td>${c.failedCount||0}</td><td><button class="text-btn" data-campaign-report="${esc(c.id)}">Details</button> <a class="text-btn" href="/api/campaigns/${encodeURIComponent(c.id)}/non-responders/csv">Non-responders</a></td></tr>`).join('')||'<tr><td colspan="5">No campaigns yet.</td></tr>'}</tbody></table></div>`);
    root().onclick=e=>{const b=e.target.closest('[data-campaign-report]');if(!b)return;const c=campaigns.find(x=>x.id===b.dataset.campaignReport);window.showDialog?.(`<div class="dialog-content"><h2>${esc(c.name)}</h2><p>${c.sentCount||0} sent · ${c.failedCount||0} failed</p><div class="rule-list">${(c.details||[]).map(x=>`<div><b>${esc(x.name||x.phone)}</b><span>${esc(x.status)} ${esc(x.reason||'')}</span></div>`).join('')||'<p>No per-contact detail is recorded for this older campaign.</p>'}</div></div>`);};
  }

  async function insights(){
    const [f,t,s,sen]=await Promise.all(['/api/analytics/funnel','/api/analytics/send-time','/api/analytics/sla','/api/analytics/sentiment'].map(url=>request(url)));
    const hours=Object.entries(t.stats?.hours||{}).sort((a,b)=>Number(b[1])-Number(a[1])).slice(0,5);title('Insights','Conversion, timing, service level and sentiment—without raw JSON.');
    root().innerHTML=`<div class="metric-grid"><div class="metric-card"><span>Sent</span><strong>${f.funnel?.sent||0}</strong></div><div class="metric-card"><span>Replied</span><strong>${f.funnel?.replied||0}</strong></div><div class="metric-card"><span>Interested</span><strong>${f.funnel?.interested||0}</strong></div><div class="metric-card"><span>SLA breaches</span><strong>${s.count||0}</strong></div></div><div class="native-grid">${card('Best send times',`<div class="rule-list">${hours.map(([hour,count])=>`<div><b>${String(hour).padStart(2,'0')}:00</b><span>${count} replies</span></div>`).join('')||'<p>No timing data yet.</p>'}</div>`)}${card('Sentiment',`<div class="rule-list">${Object.entries(sen.stats||{}).map(([name,count])=>`<div><b>${esc(name)}</b><span>${count} contacts</span></div>`).join('')}</div>`)}${card('SLA attention',`<div class="rule-list">${(s.breaches||[]).slice(0,10).map(c=>`<div><b>${esc(c.name||c.jid)}</b><span>Awaiting reply</span></div>`).join('')||'<p>All current conversations are within SLA.</p>'}</div>`)}</div>`;
  }

  // The first renderer predates the CRM migration and shadows its own
  // `templates()` function with a local array. Capture edit/save actions here
  // so every edit uses the shared sv_wa_templates library and re-renders safely.
  document.addEventListener('click',event=>{const edit=event.target.closest('[data-edit-template]');if(!edit)return;event.preventDefault();event.stopImmediatePropagation();window.__sharedTemplateEditing=Number(edit.dataset.editTemplate);window.crmParityRenderers?.templates?.();},true);
  document.addEventListener('submit',event=>{if(event.target?.id!=='sharedTemplateForm')return;event.preventDefault();event.stopImmediatePropagation();let library=[];try{library=JSON.parse(localStorage.getItem('sv_wa_templates')||'[]')}catch{};const index=Number(window.__sharedTemplateEditing??-1),name=document.getElementById('sharedTemplateName').value.trim(),body=document.getElementById('sharedTemplateBody').value.trim(),clean=body.replace(/\{\{\s*name\s*\}\}/gi,'');let depth=0;for(const ch of clean){if(ch==='{')depth++;if(ch==='}')depth--;}if(!name||!body)return notify('Enter a template name and message','error');if(depth!==0)return notify('Fix unmatched { or } before saving','error');if(index>=0)library[index]={...library[index],name,body};else library.push({name,body});window.__sharedTemplateEditing=-1;localStorage.setItem('sv_wa_templates',JSON.stringify(library));window.loadTemplateSelectors?.();window.crmParityRenderers?.templates?.();notify(index>=0?'Template updated':'Template saved');},true);
  window.crmParityRenderers={templates,blacklist,calendar,pipeline,'campaign-history':history,analytics:insights};
})();
